### ISSUE TITLE
Resolution of major version returns prebuild

### ISSUE THREAD

**Issue by DeMoorJasper** [jspm/project#103]
When trying to fetch latest major version for example: `https://ga.jspm.io/npm:@babel/core@6` it returns a prerelease `6.0.0-bridge.1`

maybe this should only be returned if it's explicitly requested?

**Comment by guybedford** [comment]
@DeMoorJasper this is actually correct - we use a different logic to npm for top-level versions based on interpreting user intent. Basically if you want to install `npm:@babel/core@6` and there's only prerelease versions available, and no stable versions at all, it will install the prerelease instead of erroring.

Is this breaking another expectation or just something you wanted to clarify?

**Comment by DeMoorJasper** [comment]
@guybedford alright thanks for clarifying, it's not really breaking anything.

Just thought it always returned prereleases if it's newer than latest stable, didn't think about that `@babel/core@6` had no stable releases... the current logic seems better than npm
