### ISSUE TITLE
Errors on require path `isobject/index.cjs.js`

### ISSUE THREAD

**Issue by jaydenseric** [jspm/project#124]
The JSPM generator errors when attempting to add `graphql-react@15.0.0`:

https://generator.jspm.io/#W8rDwMDIGJpXklmSk5rCkF6UWJBRmKNblJqYXOJgaKpnoGcAAOTn9KIjAA

```
Error: No './index.cjs.js' exports subpath defined in https://ga.jspm.io/npm:isobject@4.0.0/ resolving isobject/index.cjs.js imported from https://ga.jspm.io/npm:graphql-react@15.0.0/public/index.mjs.
```

This package contains perfectly valid Node.js ESM and CJS modules, and runs fine. It seems the JSPM generator is stumbling on the require path `isobject/index.cjs.js`:

https://github.com/jaydenseric/graphql-react/blob/v15.0.0/public/Cache.js#L3

This is a perfectly valid require path; it seems the JSPM generator doesn't understand the contents of the `isobject` package correctly.

If you try adding `isobject`:

<img width="399" alt="Screen Shot 2021-09-02 at 3 07 23 pm" src="https://user-images.githubusercontent.com/1754873/131785282-b16ba685-306c-486e-a92a-079789e2ad20.png">

It only allows the subpath `./index`, but actually there is a `./index.cjs.js` file published:

https://unpkg.com/browse/isobject@4.0.0/index.cjs.js

There is no package `exports` field, so it should be ok to require or import that file using the full `isobject/index.cjs.js` path:

https://unpkg.com/browse/isobject@4.0.0/package.json

Is this just a JSPM generator bug, is there a way to manually write the import map out until this bug is fixed?

**Comment by guybedford** [comment]
Because `isobject` doesn't have an "exports" field, JSPM is automatically inferring the exports and only detecting the main and `"./index"` as you can see.

To support the `"./index.cjs.js"` variation requires telling JSPM about it.

This can be done by creating an override with the following exports field entry for the package:

```js
{
  "exports": {
    ".": "./index.cjs.js",
    "./index": "./index.js",
    "./index.cjs.js": "./index.cjs.js"
  }
}
```

I've put together this override in https://github.com/jspm/overrides/pull/8 for you, landed that, and then run a rebuild and cache clear for the isoverride@4.0.0 package.

Make sure to clear your browser cache. Then just let me know if you have any further issues.
