### ISSUE TITLE
Don't polyfill `process` when its use is guarded

### ISSUE THREAD

**Issue by jaydenseric** [jspm/project#147]
The JSPM CDN undesirably polyfills the Node.js `process` global when its use is guarded behind `if (typeof process === "object")`.

Example:

- **Source:** https://unpkg.com/browse/react-waterfall-render@2.0.0/public/WaterfallRenderContext.js
- **JSPM:** https://ga.jspm.io/npm:react-waterfall-render@2.0.0/public/WaterfallRenderContext.js

It seems this is just a bug, because the documentation suggests that other forms of guarding such as `typeof process !== 'undefined'` is supported:

https://github.com/jspm/jspm.org/blob/10a6d5a39edbd70dc341261f9beaa2bdef373c4c/docs/cdn.md?plain=1#L242

**Comment by guybedford** [comment]
Thanks for the ping on this @jaydenseric, it's been on my list for a while it was great to have someone need it.

I've fixed this issue via https://github.com/jspm/babel-plugin-transform-cjs-dew/issues/14 and pushed the fix to the builder.

Because the CDN is versioned to the builds it does old builds needs to be flushed for this to apply unfortunately. I don't currently have a cache clear request API (like we have for build prioritization in https://jspm.org/docs/api#build-queue-request) for the builder, but plan on adding one, for now you can simply ask me if there are packages you need flushed although I completely get that's not ideal.

For now, I've rebuilt and flushed this package so if you clear your local cache it should be working now properly. Again thanks for bringing this up and let me know if you hit further cases or need other packages flushed.

**Comment by jaydenseric** [comment]
Thanks for resolving this so quickly! It's much appreciated and inspires confidence.

> let me know if you hit further cases or need other packages flushed

Can we please also flush the `graphql-react` package.

A side note, but perhaps the results could be further improved:

https://ga.jspm.io/npm:react-waterfall-render@2.0.0/public/WaterfallRenderContext.js

It leaves this, which doesn't do anything:

```js
"object"===typeof process&&false;
```

**Comment by jaydenseric** [comment]
Oh, and one more question… because this plugin has `transform-cjs` in the name, will everything we're discussing about `process` work just as well if the files were ESM in `.mjs` vs CJS in `.js`?

**Comment by jaydenseric** [comment]
Hmm, the JSPM import map generator is still adding `process`:

https://generator.jspm.io/#U2JhYGBkDM0rySzJSU1hKEpNTC7RLU8sSS1KS8zJ0S1KzUtJLXIw0jPQMwAAVv+5xCsA

```json
{
  "imports": {
    "react-waterfall-render": "https://ga.jspm.io/npm:react-waterfall-render@2.0.0/public/index.mjs"
  },
  "scopes": {
    "https://ga.jspm.io/": {
      "object-assign": "https://ga.jspm.io/npm:object-assign@4.1.1/index.js",
      "process": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.12/nodelibs/browser/process-production.js",
      "react": "https://ga.jspm.io/npm:react@17.0.2/index.js",
      "react/jsx-runtime": "https://ga.jspm.io/npm:react@17.0.2/jsx-runtime.js"
    }
  }
}
```

If you add the dependencies on their own they don't pull in the `process` stuff, so it's not clear where it's coming from.

**Comment by guybedford** [comment]
I'm not getting `process` when I visit that link. It's worth noting that chrome partitions the cache so that each origin has its own cache that needs clearing... it can just sometimes be a bit fickle to clear.

I've updated the lastest version of graphql-react, let me know how that looks to you.

Agreed, we can get it simpler. I'll check the Terser config and see why that's not optimizing out when it should.

**Comment by guybedford** [comment]
> Oh, and one more question… because this plugin has transform-cjs in the name, will everything we're discussing about process work just as well if the files were ESM in .mjs vs CJS in .js?

Yes, none of these optimizations apply to ES modules because `process.env` is not defined in ES modules in the browser. If module code wants to run in the browser it should guard its process checks. And if you want "production" / "development" splits, use the "exports" / "imports" conditions to do this instead of relying on a non-standard Node.js environment pattern (for ES modules at least, for CommonJS it is accepted only).

**Comment by guybedford** [comment]
This has been resolved now, but if there are packages that need rebuilding to get the update just ping me.
