### ISSUE TITLE
can't import @apollo/client@3.4.0

### ISSUE THREAD

**Issue by mikestaub** [jspm/project#149]
I get this error: 

Error: No './index.js' exports subpath defined in https://ga.jspm.io/npm:zen-observable@0.8.15/ resolving zen-observable/index.js imported from https://ga.jspm.io/npm:zen-observable-ts@1.2.3/index.cjs.

**Comment by guybedford** [comment]
I've pushed an update which should fix this. If you clear your browser cache it should be working now.

**Comment by mikestaub** [comment]
Thanks it works! Just out of curiosity, can you link your commit that fixed it? Is there some DB that you are maintaining or are these links autogenerated somehow?

**Comment by guybedford** [comment]
Currently the build version is the `ga` part of the CDN URL, which will update yearly. So I just pushed a builder update on the URL as the fix was already included in a previous patch. More regular build updates without manual clearing may be possible in future.

Over time more of the build components are getting open sourced as it moves from more experimental monolithic code to properly architected open source projects. For example like https://github.com/jspm/babel-plugin-transform-cjs-dew. The exports field construction for any package is not part of any open source project yet.

**Comment by mikestaub** [comment]
Cool, thanks for the explanation. This project is great and I appreciate your work!
