### ISSUE TITLE
[JSPM:Generator] Error: Unable to load package configuration for package@version

### ISSUE THREAD

**Issue by abdonrd** [jspm/project#216]
Hello!

Today I try to use the JSPM:Generator and see this error:
> Error: Unable to load package configuration for package@version

> Error: Timed out waiting for the build of package@version to be ready on the JSPM CDN. Try again later, or post a JSPM project issue if the issue persists.

Not working:
https://generator.jspm.io/#U2NgYGBkLM3ULc5IzclhcCjMLM7OLNEvT03STc7PLcjPS80rKXYw0DM00DPST0rMy0stAgDkvsuFMwA

If I go back the package version, it works:
https://generator.jspm.io/#U2NgYGBkLM3ULc5IzclhcCjMLM7OLNEvT03STc7PLcjPS80rKXYw0DM00DPQT0rMy0stAgCZue7HMwA

So I assume the library must have something wrong.
How can I identify what is happening? Is there any log available?

Thanks!

**Comment by guybedford** [comment]
@abdonrd the CDN build queue sometimes takes more than an hour to build newly published packages. Work on reducing build queue times to well under 5 minutes has been a current priority and we are very close to achieving that - a lot of the slower builds at the moment are primarily due to dealing with the historical backlog that is now almost 80% worked through.

There is a build queue API to prioritize builds in the build queue which the JS generator will attempt to use before showing that error.

These problems are most visible to publishers of packages, as opposed to users of JSPM, but we appreciate better visibility would help. We're also working on dedicated package landing pages that can provide some visibility into the build process. We are just a volunteer open source project (new members are always very welcome!), so it's a work in progress, and will take time to get full visibility integrated, but that is our hope and roadmap for early next year.

**Comment by abdonrd** [comment]
Ok, thanks @guybedford! 👏

**Comment by MateoLa** [comment]
Builds are still slow and error logs would be helpful.

**Comment by guybedford** [comment]
@MateoLa youre build queue requests got delayed due to a problem in the build queue priorisation. This should be fixed now when creating new build requests with the API. The current build queue slowdown due to npm reindexing should be resolved by the weekend.
