### ISSUE TITLE
CDN build error for @clerk/clerk-js

### ISSUE THREAD

**Issue by matteeyah** [jspm/project#226]
I'm running into issues when trying to build `@clerk/clerk-js` on the CDN.

`https://api.jspm.io/build/@clerk/clerk-js@4.21.7` keeps returning the following JSON indefinitely

```json
{"error":"JSPM is still processing @clerk/clerk-js@4.21.7, this can take a few minutes!"}
```

**Comment by JayaKrishnaNamburu** [comment]
Hey @matteeyah the build requests go into a pipeline. It will take a little while sometimes to get the build done. Please try in a while and let us know here.

**Comment by guybedford** [comment]
This seems to be working correctly now? https://generator.jspm.io/#U2NhYGBkLM3ULc5IzclhcEjOSS3K1geTulnFDsZ6pnoGAPFKy+UkAA

Yes, the build API can take a few hours occasionally, although build times have been steadily improving with recent CDN optimization work.

Just let us know if you have any further issues with it.

**Comment by matteeyah** [comment]
@guybedford Unfortunately, it's still not working. The link you shared is for `@clerk/clerk-js` version `3.5.0`.

Here's a for the latest version `4.21.7` - https://generator.jspm.io/#U2NhYGBkLM3ULc5IzclhcEjOSS3K1geTulnFDiZ6RoZ65gDRkAnjJQA, it errors out with `Error: Unable to load package configuration for @clerk/clerk-js@4.21.7.`.

Version `3.5.0` is considerably out of date and is missing lots of new functionality, which is why I'm interested in the newer one.

@JayaKrishnaNamburu Yeah, I know it takes some time for the package to end up in the queue and to get processed, but I just wasn't sure how long it usually takes. The message says it might take a couple of minutes, but it's taking more than 2 full days now.

**Comment by guybedford** [comment]
@matteeyah thanks for the update here - it turns out this package was explicitly marked as a slow build previously (we have a shortlist of about 2000 packages which are effectively stopped from causing builds on the server as they are costly to build). In this case, the package was incorrectly assigned to this list - so I've removed it and you should see the relevant builds appearing now. 

Separately, we need to provide more insight into this process as all of this state is internal and not visible to users when packages are not present. I've posted https://github.com/jspm/project/issues/227 as a project for us to better provide this visibility on packages.

Please just post back if you hit any more issues.

**Comment by matteeyah** [comment]
Thanks @guybedford, that solved everything!

Thanks for opening the issue for adding more insight into the build status for every package.
