### ISSUE TITLE
Cannot resolve https://ga.jspm.io/npm:react@18.2.0/jsx-runtime (unless you add .js)

### ISSUE THREAD

**Issue by haikyuu** [jspm/project#230]
When using esbuild with automatic transform, it tries to resolve `react/jsx-runtime`. But it fails in jspm even though the resolution should work since it's correctly specified in React's package.json.

- This doesn't work: https://ga.jspm.io/npm:react@18.2.0/jsx-runtime
- This does work https://unpkg.com/react@18.2.0/jsx-runtime

**Comment by guybedford** [comment]
The `ga.jspm.io` CDN is an import map CDN - the import map is used to resolve the "exported subpath" of the package to a final module URL. This is done via the JSPM generator project which will generate the correct mappings into an import map. Eg see https://generator.jspm.io/#U2NgYGBkLM3ULc5IzclhKEpNTC5xMLTQM9Iz0M8qrtAtKs0rycxNBQC25xIlJwA.

If you want an easy browser workflow that does what you expect you can access `https://jspm.dev/react/jsx-runtime` as well, but in general import maps are preferred for performance and better caching since all URLs are uniquely cached.

**Comment by haikyuu** [comment]
Thanks @guybedford Yes indeed. It works as expected, I had an issue somewhere else *
