### ISSUE TITLE
CDN build error for https://ga.jspm.io/npm:complex.js@2.1.1/

### ISSUE THREAD

**Issue by nvh** [jspm/project#241]
_Reporting CDN Build Error._

**Comment by guybedford** [comment]
Thanks for posting, I can confirm this is triggering a stack overflow in the build process, and have a test case for it. Will hopefully be able to get a fix out on the weekend.

**Comment by Bubblyworld** [comment]
The issue seems to be [here](https://github.com/infusion/Complex.js/blob/master/complex.js#L1415) in `complex.js`. For some reason when the DEW plugin handles the `ReferencedIdentifier` "Object" the scope's parent is equal to the scope itself, which causes an [infinite loop](https://github.com/jspm/babel-plugin-transform-cjs-dew/blob/main/transform-cjs-dew.js#L1188). Struggling to reproduce on AST explorer, where the same referenced identifier has a well-behaved scope 🤔

**Comment by Bubblyworld** [comment]
<img width="1081" alt="Screenshot 2023-03-30 at 17 00 12" src="https://user-images.githubusercontent.com/6214591/228878847-d210b50e-02a8-4aa0-b630-8569e06752f1.png">
 ^ for example, this is triggered by `complex.js`

**Comment by Bubblyworld** [comment]
Reproduction of the bug is running the plugin on:

```
(function(root) {
  function Complex() {}

  if (typeof define === 'function' && define['amd']) {
    define([], function() {
      return Complex;
    });
  } else if (typeof exports === 'object') {
    Object.defineProperty(Complex, "__esModule", { 'value': true });
    Complex['default'] = Complex;
    Complex['Complex'] = Complex;
    module['exports'] = Complex;
  } else {
    root['Complex'] = Complex;
  }
})(this);

```

**Comment by Bubblyworld** [comment]
(closing as this was resolved on the builder)

**Comment by guybedford** [comment]
Reopening pending the builder update.

**Comment by guybedford** [comment]
This is _finally_ working at https://generator.jspm.io/#U2RhYGBkDM0rySzJSU1hSM7PLchJrdDLKnYw0jPUMwQA/m2L2R8A.
