### ISSUE TITLE
@uppy/dashboard issue

### ISSUE THREAD

**Issue by holman** [jspm/project#270]
Running into an issue with trying to pin `@uppy/dashboard`:

```
Error: No './dist/mini.esm.mjs' exports subpath defined in https://ga.jspm.io/npm:exifr@7.1.3/ resolving exifr/dist/mini.esm.mjs imported from https://ga.jspm.io/npm:@uppy/thumbnail-generator@3.0.3/lib/index.js.
```

**Comment by Bubblyworld** [comment]
Hey, thanks for the issue. It looks like the `jspm.io` builder detected the entry-points incorrectly for `exifr` (we inject an [`"exports"`](https://nodejs.org/dist/latest-v19.x/docs/api/packages.html#exports) field into the `package.json` of packages without one, so that everything is compliant with the node spec). Doesn't look like `exifr` is actively maintained, so I'll add an override for it.

**Comment by guybedford** [comment]
The overrides have landed, and this appears to be working in https://generator.jspm.io/#U2RhYGBkDM0rySzJSU1hcCgtKKjUT0kszkjKTyxKcTDWM9EzAABkuvrnJAA. Please report back if you have any further issues.

**Comment by jordanell** [comment]
There seems to be another issue going on with `@uppy/dashboard`, this time with lodash / throttle.

https://generator.jspm.io/#28jEwMDIGJpXklmSk5rC4FBaUFCpn5JYnJGUn1iU4mCsZ6JnCAA5maTaJAA

```
Error: No './throttle.js' exports subpath defined in https://ga.jspm.io/npm:lodash@4.17.21/ resolving lodash/throttle.js imported from https://ga.jspm.io/npm:@uppy/core@3.2.1/lib/index.js.
```

**Comment by guybedford** [comment]
@jordanell thanks for mentioning this. I ran a rebuild of lodash, and this seems to be working now! You will need to clear your browser cache.
