### ISSUE TITLE
On Aurelia Configuration Tool

### ISSUE THREAD

**Issue by adriatic** [jspm/project#35]
Guy, while I am quite aware that you do not have the time to even meet yourself - I would still dare to ask you to check this (https://github.com/aurelia-ui-toolkits/screenshots/issues/14) article and tell me whether
1. This is a pipe dream and you **do not care** about it.
2. This is a pipe dream and you **do care** about it.
3. You might be willing to advise **[us](https://github.com/aurelia-ui-toolkits)** on how to best do this.
4. You might have your own interest in advising us to build it

Note that Rob is very interested in ACT - and I believe that you should care to have Aurelia on your good side :-)

Let me know please.

Nik

**Comment by guybedford** [comment]
There is definitely cross-over here with jspm, so thanks for reaching out to discuss. I'd be interested to follow what you do here, but as you know, I can't take anything on directly. Simple suggestions are fine though. For example, (3) on the proposal is something that can be handled by a variation of `jspm clean`, so that feature may be best handled by calling into jspm, and tracking an issue in jspm to provide the ability to filter out unused maps when using `jspm clean`. Feel free to post an issue along these lines to discuss that further. The other points from briefly reading sound more Aurelia specific, but just let me know if I can help.

**Comment by adriatic** [comment]
Thanks for your response, Guy - I am quite happy to see that you found the cross-over / overlap I hoped you would see. 

Discussing the problems Aurelia users have with jspm (this is **not** critics of jspm, but rather a statement of the ratio of its complexity and amount of understanding jspm by the average Aurelia app developer) with Rob and @jeroenvinke, my friend and member of our **[Aurelia-UI-Tollkits](https://github.com/aurelia-ui-toolkits)** team, it became obvious that creating such visual tool **specific** to Aurelia would greatly benefit the whole Aurelia community.

I would dare to be even more ambitious (pending the successful implementation of ACT) and consider the Visual JSPM as it's successor if we could count on your advisory role.

**Comment by adriatic** [comment]
As I am continuing to refine my ideas, I am also trying to create better organized document that I would like to share with you expecting a reality check. It would take a week at least to get to the point where it would make sense to discuss it.

**Note**: I would never ask you do do anything more than to read something that should be worthy of your reading and I would only expect your guidance in pointing me how to do what I need to do with jspm.
