### ISSUE TITLE
cdn responds with status code 500

### ISSUE THREAD

**Issue by lazeebee** [jspm/project#46]
screenshots attached
![capture](https://user-images.githubusercontent.com/41638844/53588417-ed8c4880-3b5a-11e9-8e69-a618e4b2443a.PNG)
![capture2](https://user-images.githubusercontent.com/41638844/53588427-f2e99300-3b5a-11e9-8150-86f1f41b123a.PNG)

**Comment by guybedford** [comment]
Thanks for sharing the error, it's a huge help to be able to dig into any bugs.

The reason for this is that it is trying to create a `dew` transform of an ES module file, so the analog of this error would be like trying to do `require('x.mjs')` to load an ES module in `node --experimental-modules`.

So the issue here is rather why it is trying to load this file with the dew transform to begin with.

What was the top-level `import` you attempted here? `import('https://dev.jspm.io/lodash-es')` works fine for me on its own.

**Comment by lazeebee** [comment]
it happens in this npm package: https://dev.jspm.io/react-three-fiber

**Comment by guybedford** [comment]
So the problem here is that this file - https://unpkg.com/react-three-fiber@1.3.0/dist/index.cjs.js. Is loading from lodash-es/omit, which corresponds to this ES module File - https://unpkg.com/lodash-es@4.17.11/omit.js.

This violates CommonJS semantics, because CommonJS cannot load ES modules. So the error in jspm here is correct.

I would suggest posting an issue to the original project that it has incorrect ES module support.

**Comment by lazeebee** [comment]
But the bundlers permit that so does that mean that the cdn doesn't work for all npm packages?

**Comment by guybedford** [comment]
The CDN implements the behaviour of Node.js and `--experimental-modules`, not what bundlers implement, which have non-standard conventions that will all have to align with `node --experimental-modules` anyway when that is unflagged. The npm package semantics comes from these Node semantics, which is the definition of what it means to support an npm package.

I know it's frustrating not being able to load a package, but when Node unflags `--experimental-modules` towards the end of this year, the ecosystem will quickly fixup these issues to adapt to these new standard semantics, rather than the non-standard bundler semantics. That is the solid future foundation of module semantics in Node.

**Comment by nosideeffects** [comment]
@guybedford I am experiencing the same issue trying to import `yargs`. It is unable to create a `dew` transform for https://github.com/yargs/yargs/blob/master/lib/apply-extends.js -- but I am having trouble understanding _why_, or how I can remedy this.

**Comment by guybedford** [comment]
npm has been giving 503 errors recently - see https://status.npmjs.org/.

I'm working on a new architecture that doesn't have to be reliant on npm
stability for the Q1 2020 release.

**Comment by nosideeffects** [comment]
Well that is just incredible. Let me know if you need more eyes or hands to push that work over the finish line!

**Comment by guybedford** [comment]
The new CDN was released today at https://jspm.dev. It is quite literally impossible to get 500 errors now since it is a complete precompilation of the entire npm registry being served only as files!
