### ISSUE TITLE
Import @chakra-ui/button fails to export the contents from it

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [jspm/project#72]
The initial discussion happened in an another issue here --> https://github.com/jspm/project/issues/71#issuecomment-665784220

And the problem related to resolving the dependencies is solved here --> https://github.com/jspm/project/issues/71#issuecomment-665784220 Now when you see the jsfiddle, the package loads without any problem.

<img width="417" alt="Screenshot 2020-07-29 at 11 07 37 PM" src="https://user-images.githubusercontent.com/11075561/88833711-52385080-d1f0-11ea-8673-57cb211a7ea9.png">

But, when the module is executed it is throwing a error in the console about the exports. For more info, you use the fiddle here --> https://jsfiddle.net/ng3ufhe9/

A quick look at the file via unpkg and bundlephobia, shows that the **Button** is exported 
unpkg --> https://unpkg.com/@chakra-ui/button@1.0.0-rc.0/dist/cjs/button.js
bundle-phobia --> https://bundlephobia.com/result?p=@chakra-ui/button@1.0.0-rc.0

**Comment by guybedford** [comment]
The problem here is if you look at the package.json file - https://github.com/chakra-ui/chakra-ui/blob/develop/packages/button/package.json, this points to the "main" entry point as a CommonJS file.

CommonJS files only export a default export. They do not support named exports, as this is what Node.js does.

Also, jspm does not use the "module" package.json entry because this is also not supported in Node.js.

If the package were to use "exports" to reference the ES module file that would solve this. So basically in the pacage.json:

```js
{
  "exports": "./dist/esm/index.js"
}
```

I would recommend making a PR to the package directly at the link above if you feel like it?

This is a very common issue, I hope the description makes sense but just let me know if it doesn't.

**Comment by JayaKrishnaNamburu** [comment]
Thanks for the explanation @guybedford, i will try to make a PR to the package 😄 and update here if the merge was possible there 👍

**Comment by JayaKrishnaNamburu** [comment]
Hi @guybedford i opened a PR on the `@chakra-ui` Github. Here is the PR -> https://github.com/chakra-ui/chakra-ui/pull/1464 Please let me know if it looks ok from the jspm side 😄

**Comment by guybedford** [comment]
Great work!

**Comment by JayaKrishnaNamburu** [comment]
Itsnot much :) Thanks for all the work with jspm

**Comment by JayaKrishnaNamburu** [comment]
Closing this, as chakra-ui adopted export maps now

**Comment by guybedford** [comment]
Thank you for working on this and getting it through!
